# Generated by Django 5.1.9 on 2025-12-08 10:12

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_alter_dispatchchannel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinIOUpload',
            fields=[
                ('dispatchchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.dispatchchannel')),
                ('endpoint_url', models.CharField(blank=True, help_text='Custom endpoint URL for MinIO or S3-compatible services. Leave blank for AWS S3.', max_length=500, verbose_name='Endpoint URL')),
                ('bucket_name', models.CharField(help_text='Name of the S3 bucket to upload files to', max_length=255, verbose_name='Bucket Name')),
                ('access_key', models.CharField(help_text='AWS Access Key ID or MinIO access key', max_length=255, verbose_name='Access Key')),
                ('secret_key', models.CharField(help_text='AWS Secret Access Key or MinIO secret key', max_length=255, verbose_name='Secret Key')),
                ('prefix', models.CharField(blank=True, help_text="Prefix (folder path) for uploaded objects. E.g., 'observations/weather' will create objects like 'observations/weather/station_id/file.csv'", max_length=500, verbose_name='Object Prefix')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to use for file dates. UTC highly recommended', verbose_name='Timezone for output dates')),
                ('write_mode', models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', help_text="'Append' merges records into daily files. 'New file' creates a separate file for each observation.", max_length=20, verbose_name='Write Mode')),
                ('max_upload_workers', models.PositiveIntegerField(default=10, help_text='Maximum number of concurrent upload threads. Higher values = faster uploads but more resource usage.', verbose_name='Max Upload Workers')),
                ('use_ssl', models.BooleanField(default=False, help_text='Whether to use SSL/TLS for connections. Often disabled for local MinIO deployments.', verbose_name='Use SSL/TLS')),
                ('verify_ssl', models.BooleanField(default=False, help_text='Whether to verify SSL certificates. Usually disabled for MinIO with self-signed certs.', verbose_name='Verify SSL Certificate')),
                ('region', models.CharField(blank=True, default='us-east-1', help_text='MinIO region. Can usually be left as default.', max_length=50, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'MinIO Upload',
                'verbose_name_plural': 'MinIO Uploads',
            },
            bases=('core.dispatchchannel', models.Model),
        ),
        migrations.CreateModel(
            name='S3Upload',
            fields=[
                ('dispatchchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.dispatchchannel')),
                ('endpoint_url', models.CharField(blank=True, help_text='Custom endpoint URL for MinIO or S3-compatible services. Leave blank for AWS S3.', max_length=500, verbose_name='Endpoint URL')),
                ('bucket_name', models.CharField(help_text='Name of the S3 bucket to upload files to', max_length=255, verbose_name='Bucket Name')),
                ('access_key', models.CharField(help_text='AWS Access Key ID or MinIO access key', max_length=255, verbose_name='Access Key')),
                ('secret_key', models.CharField(help_text='AWS Secret Access Key or MinIO secret key', max_length=255, verbose_name='Secret Key')),
                ('region', models.CharField(default='us-east-1', help_text='AWS region (e.g., us-east-1, eu-west-1). For MinIO, this can usually be left as default.', max_length=50, verbose_name='Region')),
                ('use_ssl', models.BooleanField(default=True, help_text='Whether to use SSL/TLS for connections', verbose_name='Use SSL/TLS')),
                ('verify_ssl', models.BooleanField(default=True, help_text='Whether to verify SSL certificates. Disable for self-signed certificates in development.', verbose_name='Verify SSL Certificate')),
                ('prefix', models.CharField(blank=True, help_text="Prefix (folder path) for uploaded objects. E.g., 'observations/weather' will create objects like 'observations/weather/station_id/file.csv'", max_length=500, verbose_name='Object Prefix')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to use for file dates. UTC highly recommended', verbose_name='Timezone for output dates')),
                ('write_mode', models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', help_text="'Append' merges records into daily files. 'New file' creates a separate file for each observation.", max_length=20, verbose_name='Write Mode')),
                ('max_upload_workers', models.PositiveIntegerField(default=10, help_text='Maximum number of concurrent upload threads. Higher values = faster uploads but more resource usage.', verbose_name='Max Upload Workers')),
            ],
            options={
                'verbose_name': 'S3 Upload',
                'verbose_name_plural': 'S3 Uploads',
            },
            bases=('core.dispatchchannel', models.Model),
        ),
    ]
