# Generated by Django 5.1.9 on 2025-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_s3_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minioupload',
            name='use_single_timestamp',
            field=models.BooleanField(default=True, help_text='Whether to use a single timestamp column for observation times in the CSV output.If disabled, separate date and time columns will be used.', verbose_name='Use Single Timestamp column'),
        ),
        migrations.AddField(
            model_name='s3upload',
            name='use_single_timestamp',
            field=models.BooleanField(default=True, help_text='Whether to use a single timestamp column for observation times in the CSV output.If disabled, separate date and time columns will be used.', verbose_name='Use Single Timestamp column'),
        ),
    ]
